release:
  github:
    owner: MahmoodShbni
    name: Backhaul

builds:
  - id: default
    main: ./main.go
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
