name: Build Backhaul Linux AMD64

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.1'

      - name: Download dependencies
        run: go mod tidy && go mod download

      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build -ldflags="-s -w" -o backhaul ./main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backhaul-linux-amd64
          path: backhaul
          retention-days: 7
